sudo: true

language: cpp

os:
  - linux

compiler:
  - gcc

addons:
  apt:
    sources:
      - deadsnakes
      - ubuntu-toolchain-r-test
    packages:
      - python2.7
      - python2.7-dev
      # install gcc-4.8 for C++11 compatibility, #TODO remove when Travis has gcc>=4.8, (it's used for clang too, in coveralls)
      - gcc-4.8
      - cmake
      - cmake-data
      - wget

notifications:
  email:
    recipients:
      - "discourse-nupic-developers@numenta.org"
    on_success: change
    on_failure: change
  webhooks: "https://webhooks.gitter.im/e/68f77bae61efa5c931f8"

env:
  global:
  - NUPIC=$TRAVIS_BUILD_DIR/nupic
  - NAB=$TRAVIS_BUILD_DIR/NAB
  - PYTHONPATH=/home/travis/.local/lib/python2.7/site-packages
  - PATH=/home/travis/.local/bin:$PATH

before_install:
  - alias gcc='gcc-4.8'
  - alias g++='g++-4.8'
  - export CC='gcc-4.8'
  - export CXX='g++-4.8'
  - gcc --version
  - echo "Installing latest pip"
  - sudo pip uninstall pip --yes
  - (wget http://releases.numenta.org/pip/1ebd3cb7a5a3073058d0c9552ab074bd/get-pip.py && python get-pip.py --user --upgrade --ignore-installed pip setuptools wheel && rm get-pip.py)
  - pip install pycapnp --user
  - cd ${TRAVIS_BUILD_DIR}
  - NUPIC_SHA=`cat nupic_sha.txt`
  - echo "Fetching NuPIC source code at SHA ${NUPIC_SHA}"
  - git clone https://github.com/numenta/nupic.git --depth 50
  - (cd nupic && git reset --hard ${NUPIC_SHA})
  # Clone NAB
  - git clone https://github.com/numenta/NAB.git --depth 50


install:
  - echo "Installing NuPIC..."
  - cd ${NUPIC}
  - python setup.py install --user
  - echo "Installing NAB..."
  - (cd ${NAB} && python setup.py install --user)

  # - ls /home/travis/.local/lib/python2.7/site-packages
  # - pip install pytest-xdist --user

  # For regression tests.
  - pip install automatatron --user

script:

  - cd $NUPIC

  # DEBUGGING: Trying to figure out why pytest-xdist is not available when running the swarming tests
  # below.
  # - python -c "from pkg_resources import get_distribution; print repr(get_distribution('pytest-xdist'))"

  # TODO: NuPIC swarming tests are commented out because there is a problem in Travis-CI environment
  # finding the "pytest-xdist" module even though it has clearly been installed.
  # - ./scripts/run_nupic_tests.py -w || exit -1

  # NuPIC example runs
  - . ./ci/travis/script-run-examples.sh

  # Run NAB
  - cd $NAB
  - python run.py -d numenta,numentaTM --detect --score --normalize --skipConfirmation

  - cd $TRAVIS_BUILD_DIR

  # Regressions tests
  - py.test tests/
